---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frag-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: nfs持久化路径
    server: nfs地址
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frag-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi