---
apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: devops-frag-sa
spec:
  namespace: devops
  verbs:
  - create
  - update
  - delete
  - list
  apiGroup: rbac.authorization.k8s.io
  saPolicy:
    defaultPolicy:
      name: devops-frag-sa
      namespace: devops
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: devops-frag
      subjects:
      - kind: Group
        name: devops-frag-sa
        apiGroup: rbac.authorization.k8s.io
      - kind: User
        name: devops-frag-sa
        namespace: devops
