---
apiVersion: v1
kind: Service
metadata:
  name: frag
  namespace: devops
  labels:
    app: frag
spec:
 # externalTrafficPolicy: Local
  selector:
    app: frag
  type: NodePort
  ports:
  - name: web
    port: 14000
    targetPort: app-port
    nodePort: 30001